/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;

/**
 *
 * @author MODOFWAR
 */
public class HalAwalPerusahaan extends javax.swing.JFrame {

    /**
     * Creates new form Perusahaan
     */
    
    
    
    public JButton getVacancy() {
        return Vacancy;
    }

    public JButton getButtonBack() {
        return buttonBack;
    }
   
    public HalAwalPerusahaan() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public JButton getHapusPerusahaan() {
        return hapusPerusahaan;
    }


    public JButton getTambahPerusahaan() {
        return tambahPerusahaan;
    }



    public JButton getTampilkanPerusahaan() {
        return tampilkanPerusahaan;
    }

    public JButton getEditPerusahaan() {
        return editPerusahaan;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenu = new javax.swing.JPanel();
        tambahPerusahaan = new javax.swing.JButton();
        hapusPerusahaan = new javax.swing.JButton();
        tampilkanPerusahaan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        perusahaan2 = new javax.swing.JButton();
        Vacancy = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        Vacancy1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        editPerusahaan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 102, 255));

        MainMenu.setBackground(new java.awt.Color(0, 0, 0));

        tambahPerusahaan.setBackground(new java.awt.Color(255, 102, 0));
        tambahPerusahaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/output-onlinepngtools.png"))); // NOI18N
        tambahPerusahaan.setBorderPainted(false);
        tambahPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPerusahaanActionPerformed(evt);
            }
        });

        hapusPerusahaan.setBackground(new java.awt.Color(255, 102, 0));
        hapusPerusahaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/CCC.png"))); // NOI18N
        hapusPerusahaan.setBorderPainted(false);
        hapusPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPerusahaanActionPerformed(evt);
            }
        });

        tampilkanPerusahaan.setBackground(new java.awt.Color(255, 102, 0));
        tampilkanPerusahaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/DDD.png"))); // NOI18N
        tampilkanPerusahaan.setBorderPainted(false);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/F.jpg"))); // NOI18N

        perusahaan2.setBackground(new java.awt.Color(255, 102, 0));
        perusahaan2.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        perusahaan2.setForeground(new java.awt.Color(255, 255, 255));
        perusahaan2.setText("COMPANY");
        perusahaan2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        perusahaan2.setBorderPainted(false);
        perusahaan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perusahaan2ActionPerformed(evt);
            }
        });

        Vacancy.setBackground(new java.awt.Color(255, 102, 0));
        Vacancy.setFont(new java.awt.Font("Sitka Small", 0, 12)); // NOI18N
        Vacancy.setForeground(new java.awt.Color(255, 255, 255));
        Vacancy.setText("JOB VACANCY");
        Vacancy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 10, true));
        Vacancy.setBorderPainted(false);
        Vacancy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VacancyActionPerformed(evt);
            }
        });

        buttonBack.setBackground(new java.awt.Color(255, 255, 255));
        buttonBack.setForeground(new java.awt.Color(255, 255, 255));
        buttonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/33.png"))); // NOI18N
        buttonBack.setBorderPainted(false);

        Vacancy1.setBackground(new java.awt.Color(0, 0, 0));
        Vacancy1.setForeground(new java.awt.Color(255, 255, 255));
        Vacancy1.setBorderPainted(false);
        Vacancy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vacancy1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   CREATE");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("    DELETE");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("      VIEW");

        editPerusahaan.setBackground(new java.awt.Color(255, 102, 0));
        editPerusahaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/DFE.png"))); // NOI18N
        editPerusahaan.setBorderPainted(false);
        editPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPerusahaanActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("      EDIT");

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Vacancy1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(perusahaan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MainMenuLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainMenuLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(tambahPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tampilkanPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hapusPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainMenuLayout.createSequentialGroup()
                                .addComponent(editPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Vacancy))
                            .addGroup(MainMenuLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perusahaan2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vacancy1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainMenuLayout.createSequentialGroup()
                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tambahPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapusPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tampilkanPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)))
                    .addGroup(MainMenuLayout.createSequentialGroup()
                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Vacancy, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buttonBack)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPerusahaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusPerusahaanActionPerformed

    private void perusahaan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perusahaan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perusahaan2ActionPerformed

    private void tambahPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPerusahaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahPerusahaanActionPerformed

    private void VacancyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VacancyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VacancyActionPerformed

    private void Vacancy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vacancy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vacancy1ActionPerformed

    private void editPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPerusahaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPerusahaanActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(vPerusahaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(vPerusahaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(vPerusahaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(vPerusahaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new vPerusahaan().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainMenu;
    private javax.swing.JButton Vacancy;
    private javax.swing.JButton Vacancy1;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton editPerusahaan;
    private javax.swing.JButton hapusPerusahaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton perusahaan2;
    private javax.swing.JButton tambahPerusahaan;
    private javax.swing.JButton tampilkanPerusahaan;
    // End of variables declaration//GEN-END:variables
}
